### PR TITLE
Convergence Data and Updated ReadMe for Details

### PR DESCRIPTION
**Pull request by Monlevin**

### CODE REVIEW

**Comment by galbramc** [comment]
Please remove FeCFD from the directory names and use your institution or solver as an identifier instead. Also please use the template file names for the force and moments. Something along these lines:
```
TestCase1a/027_RMIT/01_SST/DPW8-AePW4_ForceMoment_v5.dat
TestCase1a/027_RMIT/02_SA/DPW8-AePW4_ForceMoment_v5.dat
```
Your forces and moments should also be grouped in the tecplot zones. All results for the same grid level but different angle of attack should be in the same zone. You also need zones for data with the same angle of attack but different grid levels in the same zone.

**Comment by galbramc** [comment]
I don't think you have addressed my requests?

**Comment by Monlevin** [comment]
Hi Marshall,Apologies I was away over the weekend. I will amend those errors by the end of the week.Sorry for any inconvenience,Truman On 11 Nov 2024, at 3:33 PM, Marshall Galbraith ***@***.***> wrote:﻿
I don't think you have addressed my requests?

**Comment by galbramc** [comment]
We want one zone for each grid level you run with varying angle of attack within the zone. These are the GRID LEVE zones in the template. We also want one zone for each angle of attack with varying grid levels. These are the ALPHA zones in the template.

**Comment by Monlevin** [comment]
Hi Marshall,

I believe I have made all the required amendments in my latest pull request.

Let me know if there is anything else that needs doing.

Sorry for any inconvenience,
Truman
________________________________

**Comment by galbramc** [comment]
@Monlevin we discovered the file
```
027_RMIT/01_SST/DPW8-AePW4_ForceMoment_v5.dat
```
is missing CMy values. Could you please add them and update the file?

**Comment by Monlevin** [comment]
Hi Marshall,Apologies for the missing data. Looking at the  ForceMoment template I don’t see CMy, what are you referring to exactly?Kind regards,TrumanOn 1 Jan 2025, at 7:37 am, Marshall Galbraith ***@***.***> wrote:﻿
@Monlevin we discovered the file
027_RMIT/01_SST/DPW8-AePW4_ForceMoment_v5.dat

is missing CMy values. Could you please add them and update the file?

**Comment by galbramc** [comment]
@Monlevin, sorry I meant CM values. I've pasted the two zones below and put stars where there is missing data.
```
ZONE T="027.01 GRID LEVEL 2"
AUXDATA Tstatic         = "271"
AUXDATA Deltat          = "-999"
AUXDATA GridFileName    = "ONERA-OAT15A_230mmChord_780mmSpan_upZ_2024_09_05_Structured_Level-2"
AUXDATA Misc            = ""
             2             240554    0.00026    0.7300   3000000.00  1.36000  0.72506339   0.01217417  0.12188747    -999
             2             240554    0.00026    0.7300   3000000.00  1.50000  0.75358044   0.013156202  0.12227465    -999
             2             240554    0.00026    0.7300   3000000.00  2.50000  0.88003452   0.025555258  **********    -999 
             2             240554    0.00026    0.7300   3000000.00  3.00000  0.8948188   0.032625681  0.11823024    -999
             2             240554    0.00026    0.7300   3000000.00  3.10000  0.89593866   0.034018301  0.11708629    -999

ZONE T="027.01 ALPHA 2.5"
AUXDATA Tstatic         = "271"
AUXDATA Deltat          = "-999"
AUXDATA GridFileName    = "Cadence unstructured mixed element"
AUXDATA Misc            = ""
             1             151003    0.00035    0.7300   3000000.00  2.50000  0.88080449   0.025483224  0.12302004    -999
             2             240554    0.00026    0.7300   3000000.00  2.50000  0.88003452   0.025555258 ************    -999 
             3             378312    0.00019    0.7300   3000000.00  2.50000  0.87723795   0.025366775  0.12230052    -999
```

**Comment by Monlevin** [comment]
Hi Marshall,

I have deleted the old file and created a pull request for a file with the missing value. If you want to manually input them the value is: 0.12305046.

Sorry for that.

Kind regards,
Truman Gerner

________________________________

**Pull request merged**
