### PR TITLE
Convergence file added

### PR DESCRIPTION
**Pull request by adithyaXLVII**
Convergence files for all cases updated and uploaded

### CODE REVIEW

**Comment by galbramc** [comment]
Rename your directories as 
```
TestCase1a/014/01_FeCFD_Periodic_BC
TestCase1a/014/02_FeCFD_Symmetric_BC
```
Please put just one force and moment file in each of these directories that contains all the grid levels in the file.

**Comment by adithyaXLVII** [comment]
Directories renamed.
Force and moments file updated according to the specified changes.

**Comment by galbramc** [comment]
Thank you for doing that. Please remove FeCFD from the directory names and use your institution or solver as an identifier instead.  Please also don't put the force and convergence files in a sub-directory. We would like something along the lines
```
TestCase1a/014/01_IIS_SU2_Periodic_BC/DPW8-AePW4_ForceMoment_v5.dat
TestCase1a/014/02_IIS_SU2_Symmetric_BC/DPW8-AePW4_ForceMoment_v5.dat
```
We need to have a discussion about the residual convergence files. You can leave those in subdirecties as you have them for now, but we might ask you to change it in the future.

**Comment by adithyaXLVII** [comment]
The directories are renamed as specified. Also updated the convergence files in the folder "TestCase1a/014/02_IISc_SU2_Periodic_BC". 

The files uploaded here contain data at every 100 iterations due to upload size constraints. However, the full convergence files with complete data have been shared via the Box link provided.

If needed, we can arrange a brief meeting to discuss any questions or issues regarding the convergence files.

**Comment by galbramc** [comment]
Every 100 iterations is just fine. We only want the gist of the convergence history.

Could you please move your institute name IIS to the 014 folder, i.e.,
```
TestCase1a/014_IISc/02_SU2_Periodic_BC
```
sorry to be picky but we are trying to get consistency amongst participants.

**Comment by adithyaXLVII** [comment]
No problem.
I’ve made the changes you suggested.

**Comment by galbramc** [comment]
Thank you very much. This looks good.

**Pull request merged**
