### PR TITLE
TestCase1a update

### PR DESCRIPTION
**Pull request by harryxu2626**
Updated steady results for TestCase1a

### CODE REVIEW

**Comment by galbramc** [comment]
What did you change to get these updated results. Part of this effort is to track what can lead to scatter, so knowing what you have changed is valuable.

**Comment by harryxu2626** [comment]
For the FUN3D results, the changes were to stop using the `first_order_iterations` option and to decrease the `schedule_cfl` and `schedule_cflturb` options from the default. 

By default `schedule_cfl` is set to 200 and `schedule_cflturb` is set to 50. I lowered the values based on how well each case was converging. 

For the unstructured cases, generally lowering it by an order of magnitude to 20 and 5 was sufficient. But for structured cases or higher alpha/higher refinement for both mesh types, lowering the values to 1 and 1 would still pose issues for good convergence, particularly for the turbulence residual.

@Luisapiccolos was the one that re-ran Fluent for the structured meshes. Previously, I believe the Fluent cases were ran with second-order pressure, and first-order for everything else (momentum, energy etc.) For the re-run, everything was set back to second-order. 

Luisa, please feel free to correct me if I've made a mistake in describing the changes you did for the re-run.

The results for the unstructured mesh using Fluent (020.02) hasn't been updated yet, so I've made a note in the README to reflect that. 

The motivation for running with first-order in the first place for both FUN3D and Fluent was that we had difficulty in converging the cases in second-order, and first-order was able to provide more reasonable residual histories. Given the anomalous results we had previously, it's obvious now that running the cases in first-order introduced more errors than we were expecting. 

Please let me know if there's anything else I can provide.

**Comment by Luisapiccolos** [comment]
In the previous submission for the 020.01, the mesh was flattened to use the 2D solver. The new submission for 020.01 now uses the original mesh (quasi-2D) with the 3D solver, because the 2D solver diverged for any run with alpha bigger than 3 deg when using second-order schemes.

**Comment by galbramc** [comment]
@harryxu2626 there were some inconsistencies in your files that @kevinholst fiex, but he unfortunately did it before this pull request was merged. Can you help resolve the merge conflict?

**Comment by harryxu2626** [comment]
@galbramc The `Resolve conflicts` button is greyed out to me since I don't have write access to the main repo. Does it say what merge conflict it's running into?

I thought it might have been the naming of those files, but that doesn't seem to be it. The only commit I saw in the main repo that seems to affect our directory was just the renaming, but am I missing something?

**Comment by galbramc** [comment]
You need to update your repo with the changes from @kevinholst and resolve the conflict in your repo. I think the pull request will update after you do.

**Comment by harryxu2626** [comment]
I don't think there's anything else I can do on my end to resolve this merge conflict without having write access to the buffet repo since these files have updated data.

@kevinholst latest commit was to rename the files, and while I've renamed the files as well on my repo, the files themselves contain different data which I think is causing this merge conflict. I think someone with write access would need to manually select my latest commit with the new files + renaming to overwrite the existing files on the buffet repo.

Alternatively, I could try replacing those four files in my repo with the versions that are on the buffet repo (which I think would allow this pull request to go through), and then start a new pull request from my repo with the updated files.

**Comment by kevinholst** [comment]
I’ll take a look at this in the morning. We’ll get it resolved.On Dec 19, 2024, at 11:56 PM, harryxu2626 ***@***.***> wrote:﻿
I don't think there's anything else I can do on my end to resolve this merge conflict without having write access to the buffet repo since these files have updated data.
@kevinholst latest commit was to rename the files, and while I've renamed the files as well on my repo, the files themselves contain different data which I think is causing this merge conflict. I think someone with write access would need to manually select my latest commit with the new files + renaming to overwrite the existing files on the buffet repo.
Alternatively, I could try replacing those four files in my repo with the versions that are on the buffet repo (which I think would allow this pull request to go through), and then start a new pull request from my repo with the updated files.

**Comment by kevinholst** [comment]
@harryxu2626 I was able to manually fix the pull request. I don't really know what happened that caused the trouble, but the forces and moments files in subdirectories 03 and 04 were causing the merge conflict. Could you take a look at your files to make sure that all of the updates were applied as expected?

**Comment by harryxu2626** [comment]
It looks like the update was applied as expected. Thanks for your help!

**Pull request merged**
